### ISSUE TITLE
Connect File Modal to Converter

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#1]
### Connect the Modal's returned File (html5) to the converter and convert the results.
- [x] Read it in FileReader
- [x] Get it in a Stream/Blob format.
- [x] Run a conversion

**Comment by Braden-Preston** [comment]
Your recent PR didn't blow up and I can see the buffer in DevTools. I will figure out the 'end of buffer' thing at a later time. I have to pray about it to remember what it was that I was directed to do last time that fixed it. Should be moderately easy to fix, but I won't have an update for a bit. Ill just PR the fix when I get it, which will hopefully be a branch that has the converted result dumped into Draft properly.

**Comment by Braden-Preston** [comment]
Current code creates a reader in convertFile2Html. Needs moved up to parent function, convertFile(), so that the reader's buffer can be fed into both File2HTML and Mammoth async functions. Everything else should work as normal, but the final result from the bake styles function should be resolved as a promise to the store that calls convertFile() from converter.js. The store will take that awaited value and stuff it into root.editorStore, so that Draft can receive the converted content without relying on window.postMessage().

**Comment by Braden-Preston** [comment]
All that was stated above is now completed in commit 9ad370186fb93f444bb8dd4a06cad23c5cdadc49 in the master branch.

Various documents convert without issue, so this is good enough to push to the initial release until other minor/intermediate issue pop up.
