### ISSUE TITLE
Evaluate need for lettersStore.currentModal 

### ISSUE THREAD

**Issue by nickpreston24** [HarvestHaven/TPOT-Toolbox#3]
Finish evaluating whether this is needful.

**Comment by Braden-Preston** [comment]
Yes and no. For right now, since there is only one app, I am having lettersStore manage modals, and the current Modal variable ensures that only one modal is visible at a time. 

Eventually, Toolbox (App Shell) would provide a mounting container (react portal) for whatever app needs to throw up a modal into that space. That means Toolbox would be responsible for managing modals on its own, in case there are ones that get stacked from multiple apps.

Once we get a little further along, we will have the app roles a little better defined (who controls what) and that will go hand in hand with state management, default settings, initializing, and managing stores, etc.

**Comment by nickpreston24** [comment]
> I am having lettersStore manage modals, and the current Modal variable ensures that only one modal is visible at a time.

There's no scenario I can think of where one would need to pass modals or types of modals along an app within state.  If you want to show only one at a time, just increment a counter via setState() and don't allow new modals within that component.  Perhaps I'm missing the problem here.

**Comment by Braden-Preston** [comment]
A bit. I still haven't ironed it out totallly, but there are two ways that are almost or pretty much hands free for managing models. One (1) is to talk to Toolbox's state and tell it to change its current modal (currently this is what we are doing), which will only toggle on the ones its managing (reference to the modal passed by children apps when they are mounted)

The other way (2) which is 100% hands free is to do it with routing, So when you hit a certain route, it pops up the modal over what page you are on. Example: /toolbox/letters/load, would popup the load modal over the Letters application rendered in the Toolbox app shell. No state management necessary, just place the modal somewhere in the Letters app's hierarchy and it will get called if the route is ever called locally. Which is what I am leaning towards and planning.

Actually, the setup doesn't exist, so I am just going to make a generic smart <RoutedModal> component which can be dropped anywhere in the hierarchy and lets a route be established at that level to render the modal. I am all for drag and drop components here, forgoing state management all together if it is possible. What you see in the code now, is just the first example, which is a bit more manual, but works better than default React modals for now.

To wrap up this issue though, yes we have a need for lettersStore.currentModal for the migration effort, but not for long. I would add the smart RoutedModal component on the next milestone.

**Comment by nickpreston24** [comment]
> so I am just going to make a generic smart component which can be dropped anywhere in the hierarchy and lets a route be established at that level to render the modal.

Why do we need a RoutedModal, or, what would it buy us (that's needful for release)?

I think this over complicates a simple modal whose only responsibility is passing back a filestream to its parent or store.
