### ISSUE TITLE
Cannot upload .doc format. Must use .docx format

### ISSUE THREAD

**Issue by AlanAgnew** [HarvestHaven/TPOT-Toolbox#31]
So, when Ronnie gives me files, they are in .doc format.

Currently, the app fails to use .doc files. However, when I save that .doc file as a .docx file in order to transform it, then that .docx file works.

Is that an intended feature?

**Comment by Braden-Preston** [comment]
Yup! The converter we wrote works only with docx formats which is an open XML based format. Many of the newest docs that Ronnie has *should* be .docx. He was at one point converting .doc and .docx into .rtf files for the original TPOT Letters program. All of these formats can be converted to .docx with Microsoft Word or Google Docs. Libre Office may be able to as well. We expect .docx in the foreseeable future, so that is why it is this way for the time being. :)

**Comment by AlanAgnew** [comment]
I haven't tried LibreOffice. It may be good for the future, but, for now, I use Windows 10 and Microsoft Word.

Nevertheless, thanks for notifying me of the .doc issue! We'll have to use .docx.
________________________________

**Comment by Braden-Preston** [comment]
Wasn't sure if you were still on Linux. Either way, we are working for every operating system because although many people at TPOT use Windows 7 and above, others prefer Mac and Linux.

BTW Alan, in the development build of Toolbox that we are currently working on, we have the file selector now limited to .docx files, so there won't be confusion when people are trying to load files. A .doc or .rtf just simply won't show up in the popup window. You can see an example of this [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file), where the file type is limited to images only. Try clicking on the demo on that page to see what it's doing. This is what we are also doing with .docx file selection inside Toolbox.

**Comment by AlanAgnew** [comment]
Ah, you say the dev build shows only docx files. Good to hear and far clearer for people.

Yes, Linux may be done in the future, Lord willing.
________________________________
